### ISSUE TITLE
Point web root to /public folder, the rest should be protected

### ISSUE THREAD

**Issue by mjpramos** [ksdev-pl/Slim-Image-Archive#2]
Hi,

First of all, great job on this app. I really need something like this.

I can't get the project up and runing because I'm unable to point the web root to the /public folder.

I added an .htaccess file in the root dir with:
RewriteEngine On
RewriteBase /mpl/mh/votacoes2/
RewriteCond %{REQUEST_URI} !public/
RewriteRule (.*) public/$1 [L]

But I always get redirected to http://localhost/dashboard/ instead of http://localhost/mpl/mh/votacoes2

Can you please enlighten me?
Thanks

**Comment by ksdev-pl** [comment]
Hi

If I remember correctly, you must point to the `/public` folder in the server configuration. In Apache it would be the Virtual Hosts configuration (I'm not using Apache so I'm not sure if it is possible to do only with `.htaccess` in the root dir). This may be helpful: https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-ubuntu-14-04-lts
